### ISSUE TITLE
制作進捗状況

### ISSUE THREAD

**Issue by noc0** [fumibako/script#1]
## 概要

ゲーム制作全体の進捗状況です。制作の進み具合をパッと見てわかりやすくする目的で作成してみます
細かい進捗管理が必要な場合は別にIssueを立てる可能性もあります
## 制作の流れ
- [x] **黒田ルート**：シナリオ、素材作成、スクリプト、ゲームへの組み込み
- [x] **四条ルート**
  - [x] シナリオ作成
  - [x] スクリプト
    - [x] テキスト表示関連タグ打ち([r][p]など)
    - [x] 背景表示指定
    - [x] 主人公表情指定
    - [x] 攻略対象表情指定
      - [x] 攻略対象仮画像作成
    - [x] 音楽(BGM)指定
    - [x] 音(SE)指定
    - [x] 微調整(ライター)
    - [x] 最終調整(スクリプト担当)
    - [x] テストプレイと修正
    - [x] ゲームへの組み込み(スクリプト担当)
  - [x] 背景
    - [x] 画像調達(フリー画像探し、写真撮影など)
    - [x] ゲームの雰囲気に合うように加工
  - [x] 立ち絵
    - [x] ラフ(ライターとイメージすり合わせ、相談)
    - [x] 線画
    - [x] 塗り
    - [x] 表情差分作成
  - [x] スチル
    - [x] ラフ(ライターとイメージすり合わせ、相談)
    - [x] 線画
    - [x] 塗り
    - [x] normal/good差分作成
- [x] **葛城宮ルート**
  - [x] シナリオ作成
  - [x] スクリプト
    - [x] テキスト表示関連タグ打ち([r][p]など)
    - [x] 背景表示指定
    - [x] 主人公表情指定
    - [x] 攻略対象表情指定
      - [x] 攻略対象仮画像作成
    - [x] 音楽(BGM)指定
    - [x] 音(SE)指定
    - [x] 微調整(ライター)
    - [x] 最終調整(スクリプト担当)
    - [x] テストプレイと修正
    - [x] ゲームへの組み込み(スクリプト担当)
  - [x] 背景
    - [x] 画像調達(フリー画像探し、写真撮影など)
    - [x] ゲームの雰囲気に合うように加工
  - [x] 立ち絵
    - [x] ラフ(ライターとイメージすり合わせ、相談)
    - [x] 線画
    - [x] 塗り
    - [x] 表情差分作成
  - [x] スチル
    - [x] ラフ(ライターとイメージすり合わせ、相談)
    - [x] 線画
    - [x] 塗り
    - [x] normal/good差分作成
- [x] **藤枝ルート**
  - [x] シナリオ作成
  - [x] スクリプト
    - [x] テキスト表示関連タグ打ち([r][p]など)
    - [x] 背景表示指定
    - [x] 主人公表情指定
    - [x] 攻略対象表情指定
      - [x] 攻略対象仮画像作成
    - [x] 音楽(BGM)指定
    - [x] 音(SE)指定
    - [x] 微調整(ライター)
    - [x] 最終調整(スクリプト担当)
    - [x] テストプレイと修正
    - [x] ゲームへの組み込み(スクリプト担当)
  - [x] 背景
    - [x] 画像調達(フリー画像探し、写真撮影など)
    - [x] ゲームの雰囲気に合うように加工
  - [x] 立ち絵
    - [x] ラフ(ライターとイメージすり合わせ、相談)
    - [x] 線画
    - [x] 塗り
    - [x] 表情差分作成
  - [x] スチル
    - [x] ラフ(ライターとイメージすり合わせ、相談)
    - [x] 線画
    - [x] 塗り
    - [x] normal/good差分作成
- [x] **財前ルート**
  - [x] シナリオ作成
  - [x] スクリプト
    - [x] テキスト表示関連タグ打ち([r][p]など)
    - [x] 背景表示指定
    - [x] 主人公表情指定
    - [x] 攻略対象表情指定
      - [x] 攻略対象仮画像作成
    - [x] 音楽(BGM)指定
    - [x] 音(SE)指定
    - [x] 微調整(ライター)
    - [x] 最終調整(スクリプト担当)
    - [x] テストプレイと修正
    - [x] ゲームへの組み込み(スクリプト担当)
  - [x] 背景
    - [x] 画像調達(フリー画像探し、写真撮影など)
    - [x] ゲームの雰囲気に合うように加工
  - [x] 立ち絵
    - [x] ラフ(ライターとイメージすり合わせ、相談)
    - [x] 線画
    - [x] 塗り
    - [x] 表情差分作成
  - [x] スチル
    - [x] ラフ(ライターとイメージすり合わせ、相談)
    - [x] 線画
    - [x] 塗り
    - [x] normal/good差分作成
- [x] **共通ルート**
  - [x] シナリオ作成(必須分)
  - [x] 背景、音楽など素材調達、加工、作成、組み込み(必須分)
  - [x] スクリプト(必須分)
    - [x] EDまで通してプレイ可能な最低限の動作(黒田ルートまで)
    - [x] バグ取り(黒田ルートまでの大きなもの)
    - [x] 他ルート組み込み後のテストプレイ
    - [x] バグ取り(他ルート組み込み後)
    - [x] 余裕があればゲーム性の改善
    - [x] 全ルート組み込み後に立ち絵調整

**Comment by b4nFWraU42** [comment]
かなり進みましたね、お疲れ様です

**Comment by noc0** [comment]
ありがとうございます
自分の作業速度が遅々としているところが気になっていまして…スピードupを試行錯誤中です

**Comment by noc0** [comment]
追加実装終了につき、Issueを閉じます。
ゲーム完成後も含め、本来の分担を超えて多くの貴重な時間を割いてくださったメンバーの皆様にはいくら感謝してもしきれない想いです。
ありがとうございます！！！ 
長い間、おつきあいいただきまして、ありがとうございました。
